import Head from "next/head";
import { useState } from "react";
import getPlates from "~/core/plates";
import { Unit } from "~/models/plates";

export default function Home() {
  const [unit, setUnit] = useState(Unit.Pounds);
  const [weight, setWeight] = useState(0);
  const [plates, setPlates] = useState([<></>]);

  return (
    <>
      <Head>
        <title>Barbell Math Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* TODO: find an icon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid h-16 content-center justify-center bg-slate-900">
        <span className="text-2xl font-bold text-white">
          Barbell Calculator
        </span>
      </div>

      <main className="flex min-h-screen flex-col items-center bg-slate-800">
        <button
          className="mb-16 mt-16 h-12 w-56 rounded bg-purple-400"
          onClick={() =>
            setUnit(unit === Unit.Kilos ? Unit.Pounds : Unit.Kilos)
          }
        >
          <span className="m-2 text-xl font-bold text-white">
            Switch to {unit === Unit.Kilos ? Unit.Pounds : Unit.Kilos}
          </span>
        </button>

        <span className="mb-2 text-xl text-white">Weight:</span>

        <div className="mb-4">
          <input
            type="number"
            name="weight"
            className="h-10 w-64 rounded bg-slate-600 text-center text-xl text-white"
            onChange={(e) => setWeight(Number(e.target.value))}
          />
        </div>

        <div className="mb-16">
          <button
            className=""
            type="submit"
            onClick={() => setPlates(getPlates(weight, unit))}
          >
            <span className="rounded bg-violet-400 p-2 font-bold text-white">
              Calculate
            </span>
          </button>
        </div>

        {plates.map((plate) => {
          // render each plate with a key to silence console error
          return <div key={crypto.randomUUID()}>{plate}</div>;
        })}
      </main>
    </>
  );
}
